apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-modular-system
  labels:
    app: nodejs-modular-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-modular-system
  template:
    metadata:
      labels:
        app: nodejs-modular-system
    spec:
      containers:
      - name: app
        image: nodejs-modular-system:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: FRAMEWORK
          value: "express"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
