apiVersion: v1
kind: Service
metadata:
  name: nodejs-modular-system
  labels:
    app: nodejs-modular-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nodejs-modular-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-modular-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: modular-system.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-modular-system
            port:
              number: 80
